- poetry.lock
- pyproject.toml
- tests/test_client.py
- tests/test_torrent.py
- transmission_rpc/client.py
- transmission_rpc/lib_types.py
- transmission_rpc/session.py
- transmission_rpc/torrent.py
- transmission_rpc/utils.py
add new NamedTuple class `transmission_rpc.lib_types.File`
BREAKING CHANGES:
`Torrent.files()` now return `List[File]`
`Client.get_files()` now return `Dict[int, List[File]]`
> refactor: add more File class instead of return a dict

- transmission_rpc/torrent.py
Added rateUpload and rateDownload properties
and docs for `id` property
close #44
> Added rateUpload and rateDownload properties

- tests/test_torrent.py
- transmission_rpc/torrent.py
- changed property progress to use property `percentDone` - RPC version 5
> Changed progress to use percentDone property

- transmission_rpc/torrent.py
> add download_dir property

- transmission_rpc/constants.py
> feat: support transmission 3.01

- docs/source/torrent.rst
- poetry.lock
- pyproject.toml
- tests/test_torrent.py
- transmission_rpc/torrent.py
```python
assert Torrent().status.downloading
assert Torrent().status.pending
```
> feat(torrent): wrap `Torrent.status` to support simple comparison with attribute 

- tests/test_client.py
- transmission_rpc/client.py
- transmission_rpc/lib_types.py
> fix: raise `TransmissionAuthError` for 403 response

- transmission_rpc/client.py
> perf(client): aviod load and dump HTTP query twice

- docs/source/index.rst
- docs/source/session.rst
- tests/test_session.py
- transmission_rpc/client.py
- transmission_rpc/session.py
> feat(session): add some `.key()` `.items()` methods

- .github/workflows/ci.yaml
- poetry.lock
- pyproject.toml
> ci: test on python 3.10

- docs/source/client.rst
- docs/source/index.rst
Relates: transmission/transmission#2606
Relates: transmission/transmission#2644
> Update transmission documentation links

- transmission_rpc/client.py
> feat: new method `Client().get_recently_active_torrents()` to get recently removed torrents

- transmission_rpc/client.py
- transmission_rpc/constants.py
> refactor: add a rpc method enum

- docs/source/client.rst
- docs/source/index.rst
- tests/test_utils.py
- transmission_rpc/__init__.py
> tests: `from_url`

- transmission_rpc/client.py
- transmission_rpc/error.py
> feat: add details in TransmissionError

- docs/source/const.rst
- docs/source/errors.rst
- docs/source/index.rst
- transmission_rpc/__init__.py
- transmission_rpc/client.py
- transmission_rpc/constants.py
> fix: deprecate `Client.locate_torrent_data`

- .github/workflows/ci.yaml
- tests/test_torrent.py
- transmission_rpc/torrent.py
> refactor: use enum `Status`

- transmission_rpc/client.py
> refactor: better method arguments maintenance

- .github/workflows/ci.yaml
- pyproject.toml
> ci: enable test on py312

- transmission_rpc/client.py
> docs: add example for tracker-list

- transmission_rpc/torrent.py
> fix(types): `Torrent.labels` should be list of str

- .github/workflows/ci.yaml
- tests/test_client.py
- tests/util.py
- transmission_rpc/client.py
> tests: group methods

- pyproject.toml
- transmission_rpc/client.py
- transmission_rpc/session.py
- transmission_rpc/torrent.py
> style: enable mypy strict

- .github/workflows/lint.yaml
- Taskfile.yaml
- docs/conf.py
- docs/enum.rst
- docs/index.rst
- docs/session.rst
- docs/torrent.rst
- poetry.lock
- pyproject.toml
- transmission_rpc/__init__.py
- transmission_rpc/client.py
- transmission_rpc/session.py
- transmission_rpc/torrent.py
- transmission_rpc/types.py
> docs: improve code

- docs/conf.py
- poetry.lock
- pyproject.toml
> docs: improve linkcode

- transmission_rpc/client.py
> refactor: remove seq id from Client

- pyproject.toml
- tests/test_utils.py
- transmission_rpc/client.py
- transmission_rpc/constants.py
- transmission_rpc/error.py
- transmission_rpc/session.py
- transmission_rpc/torrent.py
- transmission_rpc/types.py
- transmission_rpc/utils.py
> style: add `__future__.annocations`

- pyproject.toml
> build: fix docs

- pyproject.toml
Reverts trim21/transmission-rpc#476
> Revert "chore(deps): update dependency sphinx to >=8,<=8.0.2"

- tests/conftest.py
- transmission_rpc/torrent.py
- transmission_rpc/types.py
close https://github.com/trim21/transmission-rpc/issues/484
> feat(torrent)!: return `BitMap` as `.pieces` instead of base64 str

- pyproject.toml
> build: use flit as build backend

- .github/workflows/ci.yaml
> ci: add py313 to test matrix

- .github/workflows/ci.yaml
> ci:  run test weekly

- .github/workflows/lint.yaml
- docs/.readthedocs.yaml
- pyproject.toml
> ci: upgrade docs deps

- transmission_rpc/torrent.py
- Corrected the return type of `peers()` and `peers_from()`
> fix(types): incorrect return types in `peers` and `peers_from`
